var num= 2002;
console.log("variable: num " +" | " +"Datatype : " + typeof(num));
var str="Ram";
console.log("variable: str " +" | " +"Datatype : " + typeof(str));
var bool=true;
console.log("variable: bol " +" | " +"Datatype : " + typeof(bool));
var obj={name:"Gokul",lastname:"Ram"};
console.log("variable: obj " +" | " +"Datatype : " + typeof(obj));
var fun=function(){console.log("function example")};
console.log("variable: fun " +" | " +"Datatype : " + typeof(fun));
var arr=[1,2,3,4];
console.log("variable: arr " +" | " +"Datatype : " + typeof(arr));
var n=null;
console.log("variable: n   " +" | " +"Datatype : " + typeof(n));
